name: Fetch data

on:
  workflow_dispatch:
  
  workflow_run:
    workflows: ["fetch injuries"]  # Matches the name of the first workflow
    types:
      - completed 

jobs:
  fetch-process-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Data from API
        id: fetch_data
        run: |
          API_URL="https://fantasy.premierleague.com/api/bootstrap-static/"
          curl -s "$API_URL" -o new_data.json  # Fetch the new data

      - name: Compare Data
        id: compare_data
        run: |
          if ! cmp -s new_data.json data.json; then  # Compare new data with existing data
            echo "Data has changed."
            echo "changed=true" >> $GITHUB_ENV  # Set an environment variable to indicate change
          else
            echo "Data has not changed."
            echo "changed=false" >> $GITHUB_ENV  # Set an environment variable to indicate no change
          fi

      - name: Update Data File
        if: env.changed == 'true'  # Only run if data has changed
        run: |
          mv new_data.json data.json  # Move new data to the original file
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data file with new data"
          git push origin main  # Replace `main` with your branch name if different
